### ISSUE TITLE
Undefined array key "type"

### ISSUE THREAD

**Issue by samdark** [egulias/EmailValidator#321]
I'm getting `Undefined array key "type"` error from time to time at production:

```php
    private function validateMxRecord($dnsRecord) : bool
    {
        if ($dnsRecord['type'] !== 'MX') {
            return true;
        }
```

Relevant trace:

```
#86 /vendor/egulias/email-validator/src/Validation/DNSCheckValidation.php(170): Egulias\EmailValidator\Validation\DNSCheckValidation::validateMxRecord
#85 /vendor/egulias/email-validator/src/Validation/DNSCheckValidation.php(150): Egulias\EmailValidator\Validation\DNSCheckValidation::validateDnsRecords
#84 /vendor/egulias/email-validator/src/Validation/DNSCheckValidation.php(110): Egulias\EmailValidator\Validation\DNSCheckValidation::checkDns
#83 /vendor/egulias/email-validator/src/Validation/DNSCheckValidation.php(86): Egulias\EmailValidator\Validation\DNSCheckValidation::isValid
#82 /vendor/egulias/email-validator/src/Validation/MultipleValidationWithAnd.php(66): Egulias\EmailValidator\Validation\MultipleValidationWithAnd::isValid
#81 /vendor/egulias/email-validator/src/EmailValidator.php(37): Egulias\EmailValidator\EmailValidator::isValid
```

Email validated is `dddd@dddd.com`. It looks like `dns_get_record` might return info element w/o type specified.

**Comment by samdark** [comment]
Same issue  with more emails such as `pht_hao2052@yh.com`.

PHP version is 8.1.6 OS is latest Alpine in Docker.

**Comment by egulias** [comment]
Thanks @samdark! `dns_get_record` is tricky to test. Happy to review and merge a PR ;)

**Comment by egulias** [comment]
Hi @samdark , should be fixed in v3.2 now. Please let me know

**Comment by samdark** [comment]
I'll try upgrading and deploying it to production soon.

**Comment by samdark** [comment]
Seems the problem is gone. Thank you.
