### ISSUE TITLE
Mail not being sent because of failed validation

### ISSUE THREAD

**Issue by travelhawk** [egulias/EmailValidator#336]
After moving to a different webhosting solution, my mails in laravel app are not being sent anymore. I tracked it down to the email validation. I don't know why valied email addresses are causing this null exception. Does anyone has an idea?

See the stack trace below.

```
[2022-11-18 13:19:55] prod.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/egulias/email-validator/EmailValidator/Parser/Parser.php:147)
[stacktrace]
#0 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/egulias/email-validator/EmailValidator/Parser/Parser.php(147): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to acces...', '/home/u66871525...', 147, Array)
#1 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/egulias/email-validator/EmailValidator/Parser/Parser.php(127): Egulias\\EmailValidator\\Parser\\Parser->escaped()
#2 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/egulias/email-validator/EmailValidator/Parser/LocalPart.php(57): Egulias\\EmailValidator\\Parser\\Parser->isFWS()
#3 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/egulias/email-validator/EmailValidator/EmailParser.php(48): Egulias\\EmailValidator\\Parser\\LocalPart->parse('mf-burner@gmx.d...')
#4 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/egulias/email-validator/EmailValidator/Validation/RFCValidation.php(30): Egulias\\EmailValidator\\EmailParser->parse('mf-burner@gmx.d...')
#5 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/egulias/email-validator/EmailValidator/EmailValidator.php(37): Egulias\\EmailValidator\\Validation\\RFCValidation->isValid('mf-burner@gmx.d...', Object(Egulias\\EmailValidator\\EmailLexer))
#6 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php(633): Egulias\\EmailValidator\\EmailValidator->isValid('mf-burner@gmx.d...', Object(Egulias\\EmailValidator\\Validation\\RFCValidation))
#7 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(398): Illuminate\\Validation\\Validator->validateEmail('email', 'mf-burner@gmx.d...', Array, Object(Illuminate\\Validation\\Validator))
#8 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(277): Illuminate\\Validation\\Validator->validateAttribute('email', 'Email')
#9 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(302): Illuminate\\Validation\\Validator->passes()
#10 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(314): Illuminate\\Validation\\Validator->fails()
#11 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Validation/Factory.php(136): Illuminate\\Validation\\Validator->validate()
#12 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FoundationServiceProvider.php(53): Illuminate\\Validation\\Factory->validate(Array, Array)
#13 [internal function]: Illuminate\\Http\\Request->Illuminate\\Foundation\\Providers\\{closure}(Array)
#14 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php(110): call_user_func_array(Object(Closure), Array)
#15 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/routes/api.php(11): Illuminate\\Http\\Request->__call('validate', Array)
#16 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\RouteFileRegistrar->{closure}(Object(Illuminate\\Http\\Request))
#17 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Route.php(179): Illuminate\\Routing\\Route->runCallable()
#18 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#19 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#25 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#29 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#30 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#31 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#32 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#50 /home/u668715256/domains/hochmuth.eu/hochmuth.eu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#51 /home/u668715256/domains/hochmuth.eu/public_html/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#52 {main}
"}
```

**Comment by egulias** [comment]
Hi!
Can you post your PHP version and library version? Also the email domain would be useful.
It seems to be version 2.1.x , however I'm failing to see where the null is comming for the local part you have shared.

**Comment by travelhawk** [comment]
Okay, I think I figured it out. It is not the email validation. The Recaptcha is failing and this results in a null value. So this can be closed. Thanks for the fast reply though :)

```
<?php

use Carbon\Carbon;
use App\Mail\Contact;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

Route::post('contact', function (Request $request) {
    $request->validate([
        'name' => 'required',
        'email' => 'required|email',
        'message' => 'required',
        'captcha' => 'required',
    ]);

    // Validate captcha
    $client = new \GuzzleHttp\Client();
    $response = $client->request('POST', 'https://www.google.com/recaptcha/api/siteverify', [
        'form_params' => [
            'secret' => env('RECAPTCHA_SECRET', 'none'),
            'response' => $request->get('captcha'),
        ]
    ]);

    $data = json_decode((string) $response->getBody(), true);
    $errorMessage = "Ein Fehler ist aufgetreten. Bitte später erneut versuchen!";

    if (!$data['success']) {
        return response()->json($errorMessage, 400);
    }

    $data = $request->only(['name', 'email', 'message']);
    $data['date'] = Carbon::now()->format('d.m.Y H:i A');

    try {
        Mail::to(env('MAIL_TO'))->send(new Contact($data));
        return response()->json('Ok', 200);
    } catch (\Exception $e) {
        Log::error("Error sending email. " . $e->getMessage());
        return response()->json($errorMessage, 500);
    }
});
```
